apiVersion: v1
kind: Pod
metadata:
  name: repo_name
  labels:
    heritage: deis
    version: 2.0.0-beta
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-beta
      env:
        - name: TAR_URL
          value: tar-url
        - name : put_url
          value: puturl
        - name: BUILDPACK_URL
          value: buildurl
